// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgyOa7iBIqK7A0pNIN7PT203Jrk5HOBmo',
    appId: '1:935798911299:web:7433d590290ff244513ff6',
    messagingSenderId: '935798911299',
    projectId: 'attendance-tracer-14123',
    authDomain: 'attendance-tracer-14123.firebaseapp.com',
    storageBucket: 'attendance-tracer-14123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL6hjzE5QxvdwQn04XmTuQeGDyYSBsgAM',
    appId: '1:935798911299:android:41ecff46becef492513ff6',
    messagingSenderId: '935798911299',
    projectId: 'attendance-tracer-14123',
    storageBucket: 'attendance-tracer-14123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIlxhGbq0GDEAfEi7BJF9KcAGjiIIVusk',
    appId: '1:935798911299:ios:78f0079b34fd7645513ff6',
    messagingSenderId: '935798911299',
    projectId: 'attendance-tracer-14123',
    storageBucket: 'attendance-tracer-14123.appspot.com',
    iosBundleId: 'com.example.attendaceTracer',
  );
}
